### ISSUE TITLE
Ran n-1 not n

### ISSUE THREAD

**Issue by erin-zcode** [erin-zcode/word-repeater#1]
The code should be running the word n amount of times, but rather the code is running n-1 amount of times.

**Comment by MeetoazBhardwaj** [comment]
To fix the issue where the code is running n-1 times instead of n times, you need to change the range of the for loop to include the upper limit value n. This can be done by changing the line "for i in range(1, n):" to "for i in range(n):". This will iterate the loop n times, including the value of n.

Here's the updated code:

```
def main():
    """
    Take in a word and an integer and repeat the word n times
    """
    word = input("Enter word to repeat: ")
    n = int(input("Enter number of times to repeat: "))

    for i in range(n):
        print(word)


if __name__ == "__main__":
    main()
```
